### ISSUE TITLE
`auth0_connection` 400 Bad request for google-apps strategy

### ISSUE THREAD

**Issue by ns0092** [alexkappa/terraform-provider-auth0#334]
### Terraform Version
`0.12.29`

```
Auth0 Provider version = 0.14.0
```
### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "testing_google_connection" {
  name = "testing-google-com"
  strategy = "google-apps"
  is_domain_connection = "false"
  options {
    name   = "testing-google-com"
    domain = "test-google.com"
    client_id = jsondecode(data.aws_secretsmanager_secret_version.<secret_name>.secret_string)["client_id"]
    client_secret = jsondecode(data.aws_secretsmanager_secret_version.<secret_name>.secret_string)["client_secret"]
    api_enable_users = "true"
    disable_signup = "false"
    brute_force_protection = "true"
  }
}
```

### Expected Behavior

Creation of Google connection on auth0

### Actual Behavior

Error: 400 Bad Request: undefined is not a valid google apps domain
### Steps to Reproduce

1. `terraform apply`

### Debug Output

```
2021-02-16T14:42:45.443-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [DEBUG] setting computed for "options.0.password_history" from ComputedKeys
2021-02-16T14:42:45.444-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [DEBUG] setting computed for "options.0.password_history" from ComputedKeys
2021-02-16T14:42:45.444-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [DEBUG] setting computed for "enabled_clients" from ComputedKeys
2021-02-16T14:42:45.444-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [DEBUG] setting computed for "realms" from ComputedKeys
2021-02-16T14:42:45.445-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [WARN]: Unsupported connection strategy google-apps
2021-02-16T14:42:45.445-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [WARN]: Raise an issue with the auth0 provider in order to support it:
2021-02-16T14:42:45.445-0800 [DEBUG] plugin.terraform-provider-auth0_v0.14.0_x4: 2021/02/16 14:42:45 [WARN]: 	https://github.com/terraform-providers/terraform-provider-auth0/issues/new
2021/02/16 14:42:45 [DEBUG] auth0_connection.testing_google_connection: apply errored, but we're indicating that via the Error pointer rather than returning it: 400 Bad Request: undefined is not a valid google apps domain
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BilelAouiss** [comment]
Any solution for this?

**Comment by nicholaswold** [comment]
I think https://github.com/go-auth0/auth0/pull/212 is a prerequisite for fixing this bug, since it defines the connection strategy types that would be used in this repository.

**Comment by nicholaswold** [comment]
https://github.com/go-auth0/auth0/releases/tag/v5.16.0 includes a change that now supports google-apps connection strategies, so this repo should be unblocked now!

**Comment by ns0092** [comment]
Doesn't seem to be working in latest provider 0.21.0. So I'm guessing, provider side is still not updating to use go-auth0 changes.

**Comment by vandevusse** [comment]
Hopefully this is fixed with PR at https://github.com/alexkappa/terraform-provider-auth0/pull/398 🙏

**Comment by ns0092** [comment]
Nope. Still doesn't work 👎🏼 Tried it with `0.21.0` and its the same error

```
terraform {
  required_version = "= 0.13.1"
  required_providers {
    auth0 = {
      source  = "alexkappa/auth0"
      version = "0.21.0"
    }
  }
}

Error: 400 Bad Request: undefined is not a valid google apps domain
```

**Comment by geokollias** [comment]
Confirmed the issue on master. Locally, I've added support for `google-apps` in `flattenConnectionOptions` & `expandConnection` but the same issue still happens. The POST request to `...auth0.com/api/v2/connections` definitely contains a non-empty domain field. Is there any chance the Auth0 connection creation API expects a different field for the domain? Is it documented anywhere?

**Comment by geokollias** [comment]
Ok I made some progress. I think the request body sent currently for google-apps connection creation is wrong, so it's mostly a go-auth0/auth0 issue. Currently, go-auth0/auth0 sends:

```
{
  "name": <string>,
  "strategy": "google-apps",
  "options": {
    "client_id": <string>,
    "client_secret": <string>,
    "domain": <string>,
    "domain_aliases": [ <string>, ...], // should be "tenant_domain": <string>
    "api_enable_users": <bool>,
    "basic_profile": <bool>,            // should be "profile": <bool>
    "ext_profile": <bool>,              // should be here?
    "ext_groups": <bool>,
    "ext_admin": <bool>,                // should be "ext_is_admin": <bool>
    "ext_is_suspended": <bool>,
    "ext_agreed_terms": <bool>,
    "set_user_root_attributes": "on_each_login",
    "non_persistent_attrs": null
  }
}
```

while the Auth0 dashboard sends:

```
{
  "name": <string>,
  "strategy": "google-apps",
  "options": {
    "client_id": <string>,
    "client_secret": <string>,
    "domain": <string>,
    "tenant_domain": <string>,
    "email": <bool>,                    // should be added
    "profile": <bool>,
    "ext_agreed_terms": <bool>,
    "ext_groups": <bool>,
    "ext_is_admin": <bool>,
    "ext_is_suspended": <bool>,
    "api_enable_users": <bool>
  }
}
```

I've marked the differences between the two bodies. I'll modify the go-auth0/auth0 to send the correct fields.

**Comment by vandevusse** [comment]
> Nope. Still doesn't work 👎🏼 Tried it with `0.21.0` and its the same error
> 
> ```
> terraform {
>   required_version = "= 0.13.1"
>   required_providers {
>     auth0 = {
>       source  = "alexkappa/auth0"
>       version = "0.21.0"
>     }
>   }
> }
> 
> Error: 400 Bad Request: undefined is not a valid google apps domain
> ```

@ns0092 note although the PR has been merged it has not been released yet (v0.21.0 is the older version)

**Comment by askabelin** [comment]
The problem is still there. There is no way to create `google-apps` connection. Getting 
```
Error: 400 Bad Request: undefined is not a valid google apps domain
```
even when `options` section has both `domain` and `tenant_domain` params.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/23 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
